[theme]
background = "black"
primary = "#bd93f9"
secondary = "light black"
title = "#de0be6"
playing = "#de0be6"
playing_selected = "#de0be6"
playing_bg = "black"
highlight = "#de0be6"
highlight_bg = "#44475a"
error = "#de0be6"
error_bg = "#ff5555"
statusbar = "black"
statusbar_progress = "#bd93f9"
statusbar_bg = "#de0be6"
cmdline = "#bd93f9"
cmdline_bg = "black"
search_match = "#ff79c6"
