# Generated by nixos-generate-config. Keep machine-specific changes in this host directory.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b1751659-a790-4b7d-bcf9-e0c0f859e0e0";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-2049dc63-a811-426e-9365-757ea16aa5b2".device = "/dev/disk/by-uuid/2049dc63-a811-426e-9365-757ea16aa5b2";
  boot.initrd.luks.devices."luks-4de7db73-acb9-40bd-8c1c-4b09c7d7f3be".device = "/dev/disk/by-uuid/4de7db73-acb9-40bd-8c1c-4b09c7d7f3be";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3AF3-C668";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/ed2471ec-1154-43b0-9e28-b54ca66816a1"; }
  ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
