# Generated by nixos-generate-config. Keep machine-specific changes in this host directory.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0db67a11-53f8-4364-9c0a-400cc221861a";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8caeb1b9-9bdb-4208-97f1-a058afce3585".device = "/dev/disk/by-uuid/8caeb1b9-9bdb-4208-97f1-a058afce3585";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E223-7241";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
